#!/usr/bin/env python3
"""Run RAGOffice's exact 110-item exam through Helix memory.

The exam is generated by the current RAGOffice source, immediately snapshotted
and hashed, then ingested once into one temporary Helix mind.  The same 100
answerable questions, ten negative controls, accepted answers, required spans,
reader model, and answer prompt are retained.  Only the memory/retrieval system
changes.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import logging
import os
import re
import subprocess
import sys
import tempfile
import time
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from llm.providers.base import ProviderConfig, create_session
from tests.locomo_deep_memory_sandbox import configure_retrieval
from tests.locomo_sandbox import build_runtime, render_preconscious_context, reset_question_state
from tests.longmemeval_sandbox import (
    _append_jsonl,
    _atomic_json,
    _json_safe,
    _mean,
    _read_jsonl,
    _spatial_embeddings,
    retrieval_record,
)


logger = logging.getLogger("ragoffice_parity_sandbox")

EXPECTED_ITEMS = 110
EXPECTED_ANSWERABLE = 100
EXPECTED_CONTROLS = 10
DEFAULT_RAGOFFICE_ROOT = Path("/home/nemo/RAGOffice")
DEFAULT_OUTPUT_DIR = Path("benchmark_results/ragoffice_parity_110")

# Exact text from RAGOffice/tools/llm_client.py at snapshot time. Keeping this
# here means both systems ask Granite to follow the same answer contract.
ANSWER_PROMPT = (
    "Answer the question using only the memory context block below.\n"
    "Reply with the answer only, in as few words as possible. Do not explain, "
    "quote the context, or restate the question.\n"
    "Use the exact phrase NOT IN CONTEXT only if the context block does not "
    "contain the answer at all. Never use it alongside an answer.\n\n"
    "{context}\n\n"
    "Question: {question}\n"
    "Answer:"
)

REFUSAL_MARKERS = (
    "not in context", "not in the context", "not mentioned", "not provided",
    "cannot answer", "can't answer", "unable to answer", "no information",
    "not enough information", "does not state", "doesn't state",
    "does not contain", "doesn't contain", "not specified", "unknown",
    "i don't know", "i do not know", "n/a",
)
_ARTICLES = {"a", "an", "the"}


def normalize_answer(text: Any) -> str:
    normalized = re.sub(r"[^\w\s]", " ", str(text or "").lower())
    return " ".join(token for token in normalized.split() if token not in _ARTICLES)


def token_f1(prediction: str, ground_truth: str) -> float:
    pred = normalize_answer(prediction).split()
    gold = normalize_answer(ground_truth).split()
    if not pred or not gold:
        return 0.0
    common = set(pred) & set(gold)
    count = sum(min(pred.count(token), gold.count(token)) for token in common)
    if not count:
        return 0.0
    precision = count / len(pred)
    recall = count / len(gold)
    return (2 * precision * recall) / (precision + recall)


def contains_answer(prediction: str, ground_truth: str) -> bool:
    pred = normalize_answer(prediction).split()
    gold = normalize_answer(ground_truth).split()
    if not gold or len(gold) > len(pred):
        return False
    return any(pred[index:index + len(gold)] == gold for index in range(len(pred) - len(gold) + 1))


def is_refusal(prediction: str) -> bool:
    first_line = next(
        (line for line in str(prediction or "").splitlines() if line.strip()), "",
    ).lower()
    return any(marker in first_line for marker in REFUSAL_MARKERS)


def score_answer(item: Dict[str, Any], prediction: str) -> Dict[str, Any]:
    answerable = bool(item.get("answerable", True))
    if not answerable:
        refused = is_refusal(prediction)
        return {
            "correct": refused,
            "refused": refused,
            "exact_match": False,
            "contains_answer": False,
            "token_f1": 0.0,
        }

    golds = [str(item.get("ground_truth", ""))] + [
        str(value) for value in item.get("accepted_answers", []) if value
    ]
    required = [str(value) for value in item.get("required_spans", []) if value]
    span_match = (
        all(contains_answer(prediction, span) for span in required)
        if required else any(contains_answer(prediction, gold) for gold in golds)
    )
    refused = is_refusal(prediction) and not span_match
    return {
        "correct": bool(span_match and not refused),
        "refused": refused,
        "exact_match": any(normalize_answer(prediction) == normalize_answer(gold) for gold in golds),
        "contains_answer": span_match,
        "token_f1": round(max(token_f1(prediction, gold) for gold in golds), 6),
    }


def _canonical_hash(payload: Any) -> str:
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _git_text(root: Path, *args: str) -> str:
    try:
        process = subprocess.run(
            ["git", *args], cwd=root, capture_output=True, text=True, timeout=30,
        )
        return process.stdout.strip() if process.returncode == 0 else ""
    except Exception:
        return ""


def capture_exam(ragoffice_root: Path, output_dir: Path) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Load a prior snapshot or execute RAGOffice's generator once and freeze it."""
    snapshot_path = output_dir / "ragoffice_exam_snapshot.json"
    if snapshot_path.exists():
        exam = json.loads(snapshot_path.read_text(encoding="utf-8"))
    else:
        generator = (
            "import json; "
            "from tools.run_50q_locomo_suite import generate_50q_locomo_dataset; "
            "print(json.dumps(generate_50q_locomo_dataset()))"
        )
        process = subprocess.run(
            [sys.executable, "-c", generator],
            cwd=ragoffice_root,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if process.returncode != 0:
            raise RuntimeError(
                "RAGOffice exam generator failed: " + (process.stderr or process.stdout)[-1500:]
            )
        exam = json.loads(process.stdout)
        _atomic_json(snapshot_path, exam)

    source = {
        "ragoffice_root": str(ragoffice_root.resolve()),
        "ragoffice_commit": _git_text(ragoffice_root, "rev-parse", "HEAD"),
        "ragoffice_dirty_paths": _git_text(ragoffice_root, "status", "--short").splitlines(),
        "exam_sha256": _canonical_hash(exam),
    }
    validate_exam(exam)
    return exam, source


def validate_exam(exam: Any) -> None:
    if not isinstance(exam, dict) or not isinstance(exam.get("items"), list):
        raise ValueError("RAGOffice exam must contain an items list")
    items = exam["items"]
    answerable = [item for item in items if item.get("answerable", True)]
    controls = [item for item in items if not item.get("answerable", True)]
    if (len(items), len(answerable), len(controls)) != (
        EXPECTED_ITEMS, EXPECTED_ANSWERABLE, EXPECTED_CONTROLS,
    ):
        raise ValueError(
            f"expected 110/100/10 exam shape, got {len(items)}/{len(answerable)}/{len(controls)}"
        )
    ids = [str(item.get("id", "")) for item in items]
    if not all(ids) or len(ids) != len(set(ids)):
        raise ValueError("RAGOffice exam has empty or duplicate item IDs")
    for item in items:
        if not item.get("question") or not item.get("category"):
            raise ValueError(f"exam item {item.get('id')} lacks question/category")
        if item.get("answerable", True) and not item.get("ground_truth"):
            raise ValueError(f"answerable item {item.get('id')} lacks ground_truth")


def _memory_content(item_id: str, turn_index: int, turn: Dict[str, Any]) -> str:
    speaker = str(turn.get("speaker", "user"))
    text = str(turn.get("text", turn.get("content", "")))
    ref = f"{item_id}:t{turn_index}"
    return (
        f"[BENCHMARK ITEM: {item_id}] [TURN: {turn_index}]\n"
        f"[SESSION: {ref}]\n{speaker}: {text}"
    )


def index_exam(runtime: Dict[str, Any], items: Sequence[Dict[str, Any]]) -> Dict[str, Any]:
    """Ingest all 100 answerable conversations into one Helix mind."""
    records = []
    for item in items:
        if not item.get("answerable", True):
            continue
        for turn_index, turn in enumerate(item.get("context", []), start=1):
            ref = f"{item['id']}:t{turn_index}"
            records.append({
                "item_id": str(item["id"]),
                "turn_index": turn_index,
                "ref": ref,
                "text": str(turn.get("text", turn.get("content", ""))),
                "content": _memory_content(str(item["id"]), turn_index, turn),
            })

    physics = runtime["physics"]
    memory = runtime["memory_manager"]
    preconscious = runtime["preconscious"]
    started = time.perf_counter()
    contents = [record["content"] for record in records]
    spatial = _spatial_embeddings(physics, contents)
    semantic = physics.embed_semantic_batch(contents, is_query=False)
    expected = (len(records), physics.semantic_encoder.dim)
    if semantic.shape != expected or not np.any(np.linalg.norm(semantic, axis=1) > 1e-8):
        raise RuntimeError(f"semantic encoder returned unusable shape/vectors: {semantic.shape}")

    association_vectors = _spatial_embeddings(
        physics, [record["text"][:500] for record in records],
    )
    projection = physics.spatial_mind.memory_space.projection
    associative = getattr(preconscious, "_associative", None)
    point_refs: Dict[str, str] = {}
    ref_records: Dict[str, Dict[str, Any]] = {}
    previous_item = None
    for sequence, (record, spatial_vector, semantic_vector, association_vector) in enumerate(
        zip(records, spatial, semantic, association_vectors), start=1,
    ):
        if associative is not None and record["item_id"] != previous_item:
            associative.break_sequence()
        previous_item = record["item_id"]
        position = projection.project(spatial_vector).tolist()
        memory_id = memory.store(
            content=record["content"],
            memory_type="benchmark_turn",
            source="ragoffice_parity_history",
            importance=0.75,
            tags=[
                "ragoffice_parity", f"item:{record['item_id']}",
                f"turn:{record['turn_index']}", f"session:{record['ref']}",
            ],
            position_8d=position,
            embedding_384d=spatial_vector.tolist(),
            semantic_embedding_1024d=semantic_vector.tolist(),
            pulse_id=sequence,
        )
        point_id = physics.memory_point_id(memory_id)
        point_refs[point_id] = record["ref"]
        ref_records[record["ref"]] = record

        if associative is not None:
            association_position = projection.project(association_vector).tolist()
            cluster_id, prototype = preconscious._resolve_associative_cluster({
                "id": point_id, "content": "", "position_8d": association_position,
            })
            associative.observe(cluster_id, prototype)
        physics.step_pulse(
            thought_text="", incoming_text=None,
            cluster_centroid=np.asarray(position, dtype=np.float32),
        )

    runtime["_longmemeval_point_sessions"] = point_refs
    runtime["_ragoffice_ref_records"] = ref_records
    return {
        "turns": len(records),
        "semantic_vectors": int(physics.semantic_index.count),
        "seconds": round(time.perf_counter() - started, 3),
        "association_graph": (
            associative.get_stats() if associative is not None else {}
        ),
    }


def retrieval_scores(
    item: Dict[str, Any],
    retrieval: Dict[str, Any],
    injected_context: str,
    ref_records: Dict[str, Dict[str, Any]],
) -> Dict[str, Any]:
    support = [normalize_answer(turn.get("text", "")) for turn in item.get("support", [])]
    support = [text for text in support if text]
    context_normalized = normalize_answer(injected_context)
    hits = [text for text in support if text in context_normalized]

    refs = list(dict.fromkeys(retrieval.get("session_ids", [])))
    retrieved_texts = [
        normalize_answer(ref_records[ref]["text"])
        for ref in refs if ref in ref_records
    ]
    gold_flags = [any(text == gold for gold in support) for text in retrieved_texts]
    first_rank = next((index + 1 for index, flag in enumerate(gold_flags) if flag), None)
    return {
        "support_total": len(support),
        "support_retrieved": len(hits),
        "support_hit_rate": None if not support else round(len(hits) / len(support), 6),
        "retrieved_count": len(retrieved_texts),
        "non_gold_ratio": (
            None if not retrieved_texts else round(1 - sum(gold_flags) / len(gold_flags), 6)
        ),
        "first_support_rank": first_rank,
        "retrieved_refs": refs,
    }


def local_reader_provider(model: str, context_limit: int) -> ProviderConfig:
    return ProviderConfig(
        provider_type="ollama",
        model=model,
        context_window=context_limit,
        temperature=0.0,
        max_output_tokens=256,
        options={
            "num_ctx": context_limit,
            "num_predict": 256,
            "temperature": 0.0,
            "seed": 7,
        },
    )


def ask_question(
    runtime: Dict[str, Any],
    provider: ProviderConfig,
    question: str,
) -> Dict[str, Any]:
    """Retrieve through Helix, then use RAGOffice's exact reader prompt."""
    reset_question_state(runtime["preconscious"], runtime["physics"])
    preconscious = runtime["preconscious"]
    annotations, ambient, _belief_ids, _centroid = preconscious.inject(
        previous_thought="",
        incoming_events=[f"Operator question: {question}"],
        trigger_type="user_message",
        learn=False,
    )
    context = render_preconscious_context(annotations, ambient)
    prompt = ANSWER_PROMPT.format(context=context, question=question)
    session = create_session(
        provider, "", tool_declarations=None, tool_executor=None,
        preconscious=preconscious,
    )
    started = time.perf_counter()
    try:
        raw = session.send_message(prompt).strip()
    finally:
        session.close()
    if not raw or raw.startswith("[internal error:"):
        raise RuntimeError(raw or "local reader returned an empty answer")
    return {
        "prediction": raw,
        "injected_context": context,
        "prompt": prompt,
        "latency_ms": round((time.perf_counter() - started) * 1000, 2),
        "retrieval": retrieval_record(runtime, context),
    }


def ask_question_with_retries(
    runtime: Dict[str, Any],
    provider: ProviderConfig,
    question: str,
    *,
    max_attempts: int = 3,
) -> Dict[str, Any]:
    """Retry a complete retrieval/read cycle after transient local-model loss."""
    if max_attempts < 1:
        raise ValueError("max_attempts must be positive")
    for attempt in range(1, max_attempts + 1):
        try:
            return ask_question(runtime, provider, question)
        except Exception as exc:
            if attempt == max_attempts:
                raise
            logger.warning(
                "Local reader attempt %d/%d failed; retrying full question: %s",
                attempt, max_attempts, exc,
            )
            time.sleep(2 * attempt)
    raise AssertionError("unreachable")


def _cell(value: Any, limit: int = 120) -> str:
    text = " ".join(str(value).split()).replace("|", "\\|")
    return text if len(text) <= limit else text[:limit - 1] + "…"


def _review_name(sequence: int, item_id: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", item_id)
    return f"{sequence:03d}_{safe}.md"


def write_review(output: Path, row: Dict[str, Any]) -> None:
    lines = [
        f"# {row['sequence']:03d} — {row['id']}", "",
        f"- Category: `{row['category']}`",
        f"- Answerable: `{row['answerable']}`",
        f"- Correct under RAGOffice rules: `{row['answer']['correct']}`",
        f"- Support hit rate: `{row['retrieval_scores']['support_hit_rate']}`",
        "", "## Question", "", row["question"],
        "", "## Gold", "", row["ground_truth"] or "*(negative control)*",
        "", "## Helix + Granite answer", "", row["prediction"],
        "", "## Scoring", "", "```json",
        json.dumps({
            "answer": row["answer"],
            "retrieval": row["retrieval_scores"],
            "helix_retrieval_stats": row["retrieval"]["stats"],
        }, indent=2), "```", "",
        "<details><summary>Injected Helix context</summary>", "",
        f"<pre>{html.escape(row['injected_context'])}</pre>", "", "</details>", "",
        "<details><summary>Exact source conversation and gold support</summary>", "",
        f"<pre>{html.escape(json.dumps({'context': row['source_context'], 'support': row['support']}, indent=2))}</pre>",
        "", "</details>",
    ]
    path = output / "review" / _review_name(row["sequence"], row["id"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def rebuild_reports(output: Path, manifest: Dict[str, Any], rows: Sequence[Dict[str, Any]]) -> None:
    rows = sorted(rows, key=lambda row: row["sequence"])
    answerable = [row for row in rows if row["answerable"]]
    controls = [row for row in rows if not row["answerable"]]
    by_category: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for row in rows:
        by_category[row["category"]].append(row)

    summary = {
        "status": "complete" if len(rows) == manifest["items"] else "incomplete",
        "completed": len(rows),
        "target": manifest["items"],
        "answerable_correct": sum(row["answer"]["correct"] for row in answerable),
        "answerable_total": len(answerable),
        "answer_accuracy": round(_mean(float(row["answer"]["correct"]) for row in answerable), 6),
        "negative_controls_correct": sum(row["answer"]["correct"] for row in controls),
        "negative_controls_total": len(controls),
        "support_hit_rate": round(_mean(
            float(row["retrieval_scores"]["support_hit_rate"])
            for row in answerable if row["retrieval_scores"]["support_hit_rate"] is not None
        ), 6),
        "mean_non_gold_ratio": round(_mean(
            float(row["retrieval_scores"]["non_gold_ratio"])
            for row in rows if row["retrieval_scores"]["non_gold_ratio"] is not None
        ), 6),
        "by_category": {
            category: {
                "questions": len(category_rows),
                "correct": sum(row["answer"]["correct"] for row in category_rows),
                "support_hit_rate": round(_mean(
                    float(row["retrieval_scores"]["support_hit_rate"])
                    for row in category_rows
                    if row["retrieval_scores"]["support_hit_rate"] is not None
                ), 6),
            }
            for category, category_rows in sorted(by_category.items())
        },
    }
    _atomic_json(output / "summary.json", summary)
    with (output / "hypotheses.jsonl").open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps({"id": row["id"], "hypothesis": row["prediction"]}) + "\n")

    report = [
        "# RAGOffice exam through Helix", "",
        f"Status: **{summary['status']}** ({len(rows)}/{manifest['items']})", "",
        f"- Answerable accuracy: **{summary['answerable_correct']}/{summary['answerable_total']} "
        f"({summary['answer_accuracy']:.1%})**",
        f"- Negative controls: **{summary['negative_controls_correct']}/{summary['negative_controls_total']}**",
        f"- Gold-support hit rate: **{summary['support_hit_rate']:.1%}**",
        f"- Mean non-gold ratio: **{summary['mean_non_gold_ratio']:.1%}**", "",
        "The answer score uses the same accepted-answer/span/refusal rules as RAGOffice. "
        "The memory and injected context are Helix's.", "",
        "## Categories", "", "| Category | Correct | Questions | Support hit |",
        "|---|---:|---:|---:|",
    ]
    for category, stats in summary["by_category"].items():
        report.append(
            f"| {category} | {stats['correct']} | {stats['questions']} | {stats['support_hit_rate']:.1%} |"
        )
    report.extend([
        "", "## Manual review", "",
        "| # | ID | Category | Question | Gold | Prediction | Correct | Support |",
        "|---:|---|---|---|---|---|---:|---:|",
    ])
    for row in rows:
        name = _review_name(row["sequence"], row["id"])
        report.append(
            f"| {row['sequence']} | [{row['id']}](review/{name}) | {row['category']} | "
            f"{_cell(row['question'], 80)} | {_cell(row['ground_truth'], 45)} | "
            f"{_cell(row['prediction'], 70)} | {int(row['answer']['correct'])} | "
            f"{row['retrieval_scores']['support_hit_rate']} |"
        )
    (output / "manual_review.md").write_text("\n".join(report), encoding="utf-8")


def run_parity_exam(
    *,
    ragoffice_root: str,
    output_dir: str,
    model: str = "granite4.1:8b",
    context_limit: int = 128_000,
    max_questions: int = EXPECTED_ITEMS,
    resume: bool = False,
    dry_run: bool = False,
) -> bool:
    if max_questions < 1 or max_questions > EXPECTED_ITEMS:
        raise ValueError(f"max_questions must be 1..{EXPECTED_ITEMS}")
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    exam, source = capture_exam(Path(ragoffice_root), output)
    items = exam["items"][:max_questions]

    if dry_run:
        print(
            f"RAGOffice parity exam valid: {len(exam['items'])} items, "
            f"{sum(item.get('answerable', True) for item in exam['items'])} answerable, "
            f"{sum(len(item.get('context', [])) for item in exam['items'])} turns, "
            f"sha256={source['exam_sha256']}"
        )
        return True

    configure_retrieval("frontier", True, context_limit)
    os.environ["HELIX_MRAG_RENDER_MODE"] = "verbatim"
    provider = local_reader_provider(model, context_limit)
    manifest = {
        "schema_version": 1,
        "created_at": time.strftime("%Y-%m-%d %H:%M:%S %z"),
        **source,
        "items": len(items),
        "selected_ids": [item["id"] for item in items],
        "reader_backend": "ollama",
        "reader_model": model,
        "reader_prompt_sha256": hashlib.sha256(ANSWER_PROMPT.encode()).hexdigest(),
        "context_limit": context_limit,
        "history_scope": "one shared isolated Helix mind",
        "exam_learns": False,
    }
    manifest_path = output / "manifest.json"
    details_path = output / "details.jsonl"
    if manifest_path.exists():
        if not resume:
            raise FileExistsError(f"output exists; use --resume: {output}")
        existing = json.loads(manifest_path.read_text(encoding="utf-8"))
        guarded = (
            "exam_sha256", "items", "selected_ids", "reader_backend",
            "reader_model", "reader_prompt_sha256", "context_limit",
        )
        mismatch = [key for key in guarded if existing.get(key) != manifest.get(key)]
        if mismatch:
            raise ValueError(f"resume manifest differs in: {', '.join(mismatch)}")
        manifest = existing
    else:
        _atomic_json(manifest_path, manifest)

    rows = _read_jsonl(details_path)
    completed = {row["id"] for row in rows}
    for row in rows:
        write_review(output, row)

    with tempfile.TemporaryDirectory(prefix="helix_ragoffice_parity_") as tmp_dir:
        runtime = build_runtime(tmp_dir)
        runtime["physics"]._semantic_index_path = None
        runtime["physics"]._save_attention = lambda: None
        ingest = index_exam(runtime, exam["items"])
        logger.info(
            "Indexed exact RAGOffice exam: %d turns in %.1fs",
            ingest["turns"], ingest["seconds"],
        )
        ref_records = runtime["_ragoffice_ref_records"]

        for sequence, item in enumerate(items, start=1):
            if item["id"] in completed:
                continue
            logger.info("[%d/%d] %s %s", sequence, len(items), item["id"], item["category"])
            result = ask_question_with_retries(runtime, provider, item["question"])
            retrieval_eval = retrieval_scores(
                item, result["retrieval"], result["injected_context"], ref_records,
            )
            answer_eval = score_answer(item, result["prediction"])
            row = {
                "sequence": sequence,
                "id": item["id"],
                "category": item["category"],
                "answerable": bool(item.get("answerable", True)),
                "question": item["question"],
                "ground_truth": item.get("ground_truth", ""),
                "accepted_answers": item.get("accepted_answers", []),
                "required_spans": item.get("required_spans", []),
                "source_context": item.get("context", []),
                "support": item.get("support", []),
                "prediction": result["prediction"],
                "answer": answer_eval,
                "retrieval_scores": retrieval_eval,
                "retrieval": result["retrieval"],
                "injected_context": result["injected_context"],
                "reader_latency_ms": result["latency_ms"],
                "ingest": ingest,
            }
            _append_jsonl(details_path, row)
            write_review(output, row)
            rows.append(row)
            completed.add(item["id"])
            rebuild_reports(output, manifest, rows)
            logger.info(
                "[%d/%d] correct=%s support=%s prediction=%r",
                sequence, len(items), answer_eval["correct"],
                retrieval_eval["support_hit_rate"], result["prediction"][:120],
            )

    rebuild_reports(output, manifest, rows)
    return len(rows) == len(items)


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    # Memory contents can be thousands of characters; keep the terminal a
    # progress stream while full content remains in per-question review pages.
    logging.getLogger("helix.core.preconscious").setLevel(logging.WARNING)
    logging.getLogger("httpx").setLevel(logging.WARNING)

    parser = argparse.ArgumentParser(description="Run RAGOffice's exact exam through Helix")
    parser.add_argument("--ragoffice-root", default=str(DEFAULT_RAGOFFICE_ROOT))
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--model", default="granite4.1:8b")
    parser.add_argument("--context-limit", type=int, default=128_000)
    parser.add_argument("--max-questions", type=int, default=EXPECTED_ITEMS)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    try:
        success = run_parity_exam(
            ragoffice_root=args.ragoffice_root,
            output_dir=args.output_dir,
            model=args.model,
            context_limit=max(1024, args.context_limit),
            max_questions=args.max_questions,
            resume=args.resume,
            dry_run=args.dry_run,
        )
    except Exception as exc:
        logger.exception("RAGOffice parity run failed: %s", exc)
        success = False
    raise SystemExit(0 if success else 1)


if __name__ == "__main__":
    main()
